language: node_js
node_js:
- "4"
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-set-default
      - oracle-java8-installer
script: sh build.sh
deploy:
  provider: openshift
  skip_cleanup: true
  deployment_branch: HEAD:master
  condition: "$TRAVIS_BRANCH = master"
  app: beer
  user:
    secure: "rXF9I7rejANsafLKERgg1DK9gFrhEGa3PeaOT4k5BEJWGu3bA8J9FdOoHPRvawRg57GCBkLIwwU2q5LpH67AFdKeEGcv/CfM/iiQhMZfCXFp0JUIxwFjKwwy9kMxiIKV+GPRiskj6nYcqhnQwDRYFa7F9cjXuYySfVwgPGb6bP/1KyO0dst3X7JdyjxOpdgNyg8FAevhFz3q7wGq+yYkNl9uUjEIKLSvxXo4DtBCpD/qt5c9HHVIDIfv9U2GUVO5Mp5V4FFnUzms4SKbhRsSmcs/vIM53Kb56kK51WjFyoepxCsfzKre8MMWTvTmxdD2xXHuOAMN6SqKQ99jKK+/8Wpk451BMaD26QB9g/nkmFci8lfSDVws+Xik0r0d++6XropNxsBd+pRXlkCmCM6pnVef1YR53kEVTCw2VRPwKHu8Wh4lnqyNk/CDrwILpdDt4idxyk/NkHY+dgRXWRhLZ7sSzi/ITU4fTwdkOcVLEqaxsQhOLwRQnbPSbWlvihUUbW0be0D/K4qNpoehXsatASi/cdDAoruRiQkFKy5TP5VCvl45/RQO0G52JOXjhoNBY1ww9HEJQQ58HPxM0jyfJto9sCzX0gBQ15wogOaA7dLCNG3rsFN+z6HWR1cyBRMYgOK7yGLDkKrd734luTnTLMWS9OWaIIvJIpB2QmaDW1I="
  password:
    secure: $MY_PASSWORD
  domain:
    secure: "POxctu6QtPu2fkWfQrer+YKQ/refEUMU5/iaXUuGn3shcvdjIDa7WeJ1oYEJ4TaBHSJITKLYp8r26rb5+ENCvBsRkCt00/44JnCVBX9QyP7zbKY3E03S1HZbUIa8E/MxKeNJjUzeBK4+sf1RGiiFj+t342f7VPiOdJtZzxrJRAdoTx33G++dNwthjX6lv0nSgWb/euHeH/KPrMZgrBIezFocn1lMeUqk04K4fx/rw6GSRJZ3ZxPmVsSsH1Mvlsckz6AT3WV+EhSdTOf/42Fp7f7uLOxWHrQmOncdHQMw2WMZ4EInFqscQ5MzDt/k4u7Ed/jcSZft4gZcnnvOqyvRewlMKaXXOEW23jMhKTeBkUOYYv8t+f+MdB95Gqn0jJcTN6im1b99bm8L4+q10aPJI3vGH65pUwESuMMEf7XdF4oVuXru3o0/OX3YnAF3BMmd1RpScdM4k6tc7perjDAena7JGNjNFlPFanck3YX8/8Yu+sch42N96fiQzGESDA0iE0CP71US9CvQkEgZwJY3yPPQPx66qQj3mlEn70beXNLJYlCNWLA0EOUdJz2qJ0D1zZtpSLT6a9+5lHnQU1fPx089le837yG1Csmba/amzdVjJmk2WZxyPvvc48MJdmrO2HpNVgb3O1mmtrl9h6jdQ7eNKi8n3hEQydIz/73F8iE="
